routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/profile', 'ProfileController@index')->name('profile');
    Route::put('/profile/update', 'ProfileController@update')->name('profile.update');
    Route::get('get/skor/habits', 'UsersPerfomanceController@getHabitsScore')->name('get.skor.habits');
});

Route::group(['middleware' => ['auth', 'role:admin']], function () {
    Route::resource('main-habits', 'MainHabitsController');
    Route::resource('sub-main-habits', 'SubMainHabitsController');
    Route::resource('habits', 'HabitsController')->except(['create']);
    Route::resource('lembaga', 'LembagaController');
    
    // add user institusi
    Route::get('lembaga/user/{id}', 'LembagaController@user')->name('lembaga.user');
    Route::post('lembaga/user/{id}/{action}', 'LembagaController@userstore')->name('lembaga.user.add');

    Route::resource('role', 'RoleController');
    Route::resource('group', 'GroupController');
    Route::resource('ayyamul-bidh', 'AyyamulBidhController');
    Route::resource('pengamalan-habits-umum', 'PengamalanHabitsUmumController');
    Route::resource('pengamalan-tadarus', 'RealitationTadarusController');
    Route::resource('pengamalan-zis', 'RealitationZisController');
});

Route::group(['middleware' => ['auth', 'role:admin instansi']], function () {
    Route::resource('group-institution', 'GroupInstitutionController');
});

Route::group(['middleware' => ['auth', 'role:admin|admin instansi']], function () {
    Route::resource('notification', 'NotificationController');
});

Route::group(['middleware' => ['auth', 'role:admin|user admin|admin instansi']], function () {
    Route::resource('user', 'UsersController');
    Route::resource('user-performance', 'UsersPerfomanceController');
    Route::get('userperformance/print', 'UsersPerfomanceController@print')->name('user-performance.print');
});

app/Models/AyyamulBidh.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AyyamulBidh extends Model
{
    protected $table = 'ayyamul_bidh';
    protected $fillable = [
        'date_hijriyah',
        'month_hijriyah',
        'year_hijriyah',
        'date_masehi',
    ];

    public function getTanggalHijriyahAttribute()
    {
        return $this->getAttribute('date_hijriyah').'-'.$this->getAttribute('month_hijriyah').'-'.$this->getAttribute('year_hijriyah');
    }

    public function getTanggalMasehiAttribute()
    {
        return date('d-m-Y', strtotime($this->getAttribute('date_masehi')));
    }

    public function scopeFilter($query, $request)
    {
        if ($request === null) {
            return $query;
        }

        if ($request->get('tanggal_masehi') !== null) {
            $query->where('date_masehi', 'LIKE', '%'.$request->get('tanggal_masehi').'%');
        }

        if ($request->get('bulan') !== null) {
            $query->whereMonth('date_masehi', $request->get('bulan'));
        }

        if ($request->get('tahun') !== null) {
            $query->whereYear('date_masehi', $request->get('tahun'));
        }

        return $query;
    }
}

app/Http/Controllers/Api/AyyamulBidhController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\AyyamulBidh;
use Exception;
use Illuminate\Http\Request;

class AyyamulBidhController extends Controller
{
    use TraitResponse;

    public function getAyyamulBidh(Request $request)
    {
        try {
            $data = AyyamulBidh::filter($request)->get();

            return $this->response('true', 'Berhasil mengambil data Ayyamul Bidh', $data);
        } catch (Exception $e) {
            return $this->response('false', $e->message());
        }
    }
}

app/Http/Controllers/AyyamulBidhController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\AyyamulBidhRequest;
use App\Repositories\AyyamulBidhRepository;

class AyyamulBidhController extends Controller
{
    public function __construct(AyyamulBidhRepository $repo)
    {
        $this->model = $repo;
        $this->title = 'Ayyamul Bidh';
        $this->module = 'ayyamul_bidh';
        $this->request = AyyamulBidhRequest::class;
        $this->view = [
            'filter' => [
                'tanggal_masehi' => 'date_normal',
            ],
        ];
    }

    public function index()
    {
        return parent::index()->with($this->view);
    }
}

resources/views/admin/ayyamul_bidh/create.blade.php
@extends('layouts.app')

@section('content')

		<!-- Horizontal Form -->
		<div class="box box-info">
		  <div class="box-header with-border">
			<h3 class="box-title">{{ $title_document }}</h3>
		  </div>
		  <!-- /.box-header -->
		  <!-- form start -->
		{{ Form::open(['route' => $module_url->store, 'method' => 'POST','files' => true]) }}
			<div class="box-body">
			  @include($form)
			</div>
			<!-- /.box-body -->
			<div class="box-footer">
				<button type="submit" class="btn btn-primary pull-right btn-simpan" dusk="btn-simpan">Simpan</button>
			</div>
			<!-- /.box-footer -->
		{{ Form::close() }}
		</div>

@endsection

@section('js')
@endsection

resources/views/admin/ayyamul_bidh/edit.blade.php
@extends('layouts.app')

@section('content')

		<!-- Horizontal Form -->
		<div class="box box-info">
		  <div class="box-header with-border">
			<h3 class="box-title">{{ $title_document }}</h3>
		  </div>
		  <!-- /.box-header -->
		  <!-- form start -->
		{{ Form::model($item, ['route' => [$module_url->update, $item->id], 'method' => 'PUT', 'files' => true]) }}
			<div class="box-body">
			  @include($form)
			</div>
			<!-- /.box-body -->
			<div class="box-footer">
				<button type="submit" class="btn btn-primary pull-right btn-simpan" dusk="btn-simpan">Simpan</button>
			</div>
			<!-- /.box-footer -->
		{{ Form::close() }}
		</div>

@endsection

@section('js')
@endsection

resources/views/admin/ayyamul_bidh/form.blade.php
<div class="form-group {{ $errors->has('date_hijriyah') ? ' has-error' : '' }}">
	<label for="date_hijriyah">Tanggal Hijryiah</label>
	{{ Form::number('date_hijriyah', old('date_hijriyah'), ['class' => 'form-control', 'id' => 'date_hijriyah', 'min' => 1, 'max' => 31, 'placeholder' => 'Tanggal (angka)', 'required']) }}
	{!! $errors->first('date_hijriyah', '<p class="help-block">:message</p>') !!}
</div>
	
<div class="form-group {{ $errors->has('month_hijriyah') ? ' has-error' : '' }}">
	<label for="month_hijriyah">Bulan Hijriyah</label>
	{{ Form::number('month_hijriyah', old('month_hijriyah'), ['class' => 'form-control', 'id' => 'month_hijriyah', 'min' => 1, 'max' => 12, 'placeholder' => 'Bulan (angka)', 'required']) }}
	{!! $errors->first('month_hijriyah', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group {{ $errors->has('year_hijriyah') ? ' has-error' : '' }}">
	<label for="year_hijriyah">Tahun Hijriyah</label>
	{{ Form::number('year_hijriyah', old('year_hijriyah'), ['class' => 'form-control', 'id' => 'year_hijriyah', 'placeholder' => 'Tahun', 'required']) }}
	{!! $errors->first('year_hijriyah', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group {{ $errors->has('date_masehi') ? ' has-error' : '' }}">
	<label for="date_masehi">Tanggal & Tahun Masehi</label>
	{{ Form::text('date_masehi', old('date_masehi'), ['class' => 'form-control datetime', 'id' => 'date_masehi', 'placeholder' => 'Tahun Masehi', 'required']) }}
	{!! $errors->first('date_masehi', '<p class="help-block">:message</p>') !!}
</div>

@section('js')
	<script>
		$('.datetime').datetimepicker({
			format: 'DD-MM-YYYY'
		});
	</script>
@endsection

resources/views/admin/ayyamul_bidh/index.blade.php
@extends('layouts.app')

@section('content')
@include('layouts.filter')
{{-- {!! session() !!} --}}
<div class="clearfix"></div>
<br>
<div class="box box-success">
    <div class="box-header with-border ">
        <h3 class="box-title">{{ $title_document }}</h3>

    </div>
    <div class="box-body">
        @if ($items->isEmpty())
        <div class="alert alert-warning alert-dismissible " role="alert">
            <strong>Informasi</strong>

            Tidak Ada Data
        </div>
    @else
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th width="1%">#</th>
                        <th>Tanggal Hijriyah</th>
                        <th>Tanggal Masehi</th>
                        <th width="15%">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($items as $item)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $item->tanggal_hijriyah }}</td>
                            <td>{{ $item->tanggal_masehi }}</td>
                            <td>
                                    <a href="{{ route($module_url->edit, $item->id) }}" class="btn btn-warning waves-effect waves-light" dusk="btn-option-edit-{{ $item->id }}"> <i class="fa fa-pencil-square-o"></i></a>
                                
                                    <a class="btn btn-danger waves-effect waves-light" data-dismiss="modal" onclick="$('#delete-{{ $item->id }}').modal('show')" dusk="hapus-{{ $item->id }}"><i class="fa fa-trash"></i></a>
    
                                    <div class="modal fade" role="dialog" tabindex="-1" id="delete-{{ $item->id }}">
                                        <div class="modal-dialog modal-sm" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h4 class="modal-title">Perhatian!</h4>
                                                </div>
                                                <div class="modal-body">
                                                    Hapus data, Yakin ?
    
                                                    <div class="row" style="margin-top:50px;">
                                                        <div class="col-md-6">
                                                            <a href="{{ route('ayyamul-bidh.destroy', $item->id) }}" data-method="DELETE" class="btn btn-danger" dusk="yesd-{{ $item->id }}">Ya, hapus!</a>
                                                        </div>
                                                        <div class="col-md-6">
                                                            <a class="btn btn-inverse" data-dismiss="modal" onclick="$('#option-{{ $item->id }}').modal('show')">Batalkan</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

    @endif
    </div>
    <!-- /.box-body -->
    <div class="box-footer">
        <div>
            {{ $items->appends(Request::all())->links() }}
        </div>        
    </div>
    <!-- /.box-footer-->
</div>


@endsection

@section('script')
    <script src="{{ asset('js/laravel.js') }}"></script>
@endsection