routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/profile', 'ProfileController@index')->name('profile');
    Route::put('/profile/update', 'ProfileController@update')->name('profile.update');
    Route::get('get/skor/habits', 'UsersPerfomanceController@getHabitsScore')->name('get.skor.habits');
});

Route::group(['middleware' => ['auth', 'role:admin']], function () {
    Route::resource('main-habits', 'MainHabitsController');
    Route::resource('sub-main-habits', 'SubMainHabitsController');
    Route::resource('habits', 'HabitsController')->except(['create']);
    Route::resource('lembaga', 'LembagaController');
    
    // add user institusi
    Route::get('lembaga/user/{id}', 'LembagaController@user')->name('lembaga.user');
    Route::post('lembaga/user/{id}/{action}', 'LembagaController@userstore')->name('lembaga.user.add');

    Route::resource('role', 'RoleController');
    Route::resource('group', 'GroupController');
    Route::resource('ayyamul-bidh', 'AyyamulBidhController');
    Route::resource('pengamalan-habits-umum', 'PengamalanHabitsUmumController');
    Route::resource('pengamalan-tadarus', 'RealitationTadarusController');
    Route::resource('pengamalan-zis', 'RealitationZisController');
});

Route::group(['middleware' => ['auth', 'role:admin instansi']], function () {
    Route::resource('group-institution', 'GroupInstitutionController');
});

Route::group(['middleware' => ['auth', 'role:admin|admin instansi']], function () {
    Route::resource('notification', 'NotificationController');
});

Route::group(['middleware' => ['auth', 'role:admin|user admin|admin instansi']], function () {
    Route::resource('user', 'UsersController');
    Route::resource('user-performance', 'UsersPerfomanceController');
    Route::get('userperformance/print', 'UsersPerfomanceController@print')->name('user-performance.print');
});

app/Models/RealitationBasic.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class RealitationBasic extends Model
{
    protected $table = 'relation_basics'; //typo
    protected $fillable = [
        'value',
        'habits_id',
        'user_id',
        'date',
    ];

    public function habits()
    {
        return $this->belongsTo(Habits::class, 'habits_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function getDateFormattedAttribute()
    {
        return date('d F Y', strtotime($this->getAttribute('date')));
    }

    public function scopeFilter($query, $request)
    {
        if ($request === null) {
            return $query;
        }

        if ($request->get('nama') !== null) {
            $query->whereHas('user', function ($query) use ($request) {
                return $query->where('name', 'like', '%'.$request->get('nama').'%');
            });
        }

        if ($request->get('tanggal') !== null) {
            $query->whereDate('date', date('Y-m-d', strtotime($request->get('tanggal'))));
        }

        if ($request->get('habits') !== null) {
            $query->whereHas('habits', function ($query) use ($request) {
                return $query->where('name', 'like', '%'.$request->get('habits').'%');
            });
        }

        if ($request->get('grup') != null) {
            $query->whereHas('user', function ($query) use ($request) {
                return $query->where('group_id', $request->get('grup'));
            });
        }

        return $query;
    }
}

app/Http/Controllers/PengamalanHabitsUmumController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PengamalanHabitsUmumRequest;
use App\Repositories\PengamalanHabitsUmumRepository;

class PengamalanHabitsUmumController extends Controller
{
    public function __construct(PengamalanHabitsUmumRepository $repo)
    {
        $this->model = $repo;
        $this->title = 'Pengamalan Habits Umum';
        $this->request = PengamalanHabitsUmumRequest::class;
        $this->module = 'pengamalan_habits_umum';
        $this->view = [
            'filter' => [
                'nama' => 'text',
                'tanggal' => 'date',
                'habits' => 'text',
                'grup' => 'select',
            ],
            'create_unactive' => true,
            'grup' => $this->model->getGroup(),
        ];
    }

    public function index()
    {
        return parent::index()->with($this->view);
    }
}

resources/views/admin/pengamalan_habits_umum/create.blade.php
@extends('layouts.app')

@section('content')

		<!-- Horizontal Form -->
		<div class="box box-info">
		  <div class="box-header with-border">
			<h3 class="box-title">{{ $title_document }}</h3>
		  </div>
		  <!-- /.box-header -->
		  <!-- form start -->
		{{ Form::open(['route' => $module_url->store, 'method' => 'POST','files' => true]) }}
			<div class="box-body">
			  @include($form)
			</div>
			<!-- /.box-body -->
			<div class="box-footer">
				<button type="submit" class="btn btn-primary pull-right" dusk="btn-simpan">Simpan</button>
			</div>
			<!-- /.box-footer -->
		{{ Form::close() }}
		</div>

@endsection

@section('js')
@endsection

resources/views/admin/pengamalan_habits_umum/edit.blade.php
@extends('layouts.app')

@section('content')

		<!-- Horizontal Form -->
		<div class="box box-info">
		  <div class="box-header with-border">
			<h3 class="box-title">{{ $title_document }}</h3>
		  </div>
		  <!-- /.box-header -->
		  <!-- form start -->
		{{ Form::model($item, ['route' => [$module_url->update, $item->id], 'method' => 'PUT', 'files' => true]) }}
			<div class="box-body">
			  @include($form)
			</div>
			<!-- /.box-body -->
			<div class="box-footer">
				<button type="submit" class="btn btn-primary pull-right" dusk="btn-simpan">Simpan</button>
			</div>
			<!-- /.box-footer -->
		{{ Form::close() }}
		</div>

@endsection

@section('js')
@endsection

resources/views/admin/pengamalan_habits_umum/form.blade.php
<div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
	<label for="name">Nama</label>
	{{ Form::text('name', old('name'), ['class' => 'form-control', 'id' => 'name', 'placeholder' => 'Nama', 'required']) }}
	{!! $errors->first('name', '<p class="help-block">:message</p>') !!}
</div>

resources/views/admin/pengamalan_habits_umum/index.blade.php
@extends('layouts.app')

@section('content')
@include('layouts.filter')
{{-- {!! session() !!} --}}
<div class="clearfix"></div>
<br>
<div class="box box-success">
    <div class="box-header with-border ">
        <h3 class="box-title">{{ $title_document }}</h3>
    </div>
    <div class="box-body">
        @if ($items->isEmpty())
        <div class="alert alert-warning alert-dismissible" role="alert">
            <strong>Informasi</strong>

            Tidak Ada Data
        </div>
    @else
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th width="1%">#</th>
                        <th>Tanggal</th>
                        <th>Nama</th>
                        <th>Habits</th>
                        <th>Nilai</th>
                        <th>Group</th>
                        <th width="10%">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($items as $item)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $item->date_formatted }}</td>
                            <td>{{ $item->user->name }}</td>
                            <td>{{ $item->habits->name }}</td>
                            <td>{{ $item->value }}</td>
                            <td>{{ $item->user->group->name ?? '-' }}</td>
                            <td>

                                <a href="{{ route($module_url->edit, $item->id) }}" class="btn btn-warning waves-effect waves-light" dusk="btn-option-edit-{{ $item->id }}"> <i class="fa fa-pencil-square-o"></i></a>
                                
                                <a class="btn btn-danger waves-effect waves-light" data-dismiss="modal" onclick="$('#delete-{{ $item->id }}').modal('show')" dusk="hapus-{{ $item->id }}"><i class="fa fa-trash"></i></a>

                                <div class="modal fade" role="dialog" tabindex="-1" id="delete-{{ $item->id }}">
                                    <div class="modal-dialog modal-sm" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4 class="modal-title">Perhatian!</h4>
                                            </div>
                                            <div class="modal-body">
                                                Hapus data, Yakin ?

                                                <div class="row" style="margin-top:50px;">
                                                    <div class="col-md-6">
                                                        <a href="{{ route('pengamalan-habits-umum.destroy', $item->id) }}" data-method="DELETE" class="btn btn-danger" dusk="yesd-{{ $item->id }}">Ya, hapus!</a>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <a class="btn btn-inverse" data-dismiss="modal" onclick="$('#option-{{ $item->id }}').modal('show')">Batalkan</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

    @endif
    </div>
    <!-- /.box-body -->
    <div class="box-footer">
        <div>
            {{ $items->appends(Request::all())->links() }}
        </div>        
    </div>
    <!-- /.box-footer-->
</div>


@endsection

@section('script')
    <script src="{{ asset('js/laravel.js') }}"></script>
@endsection