routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/profile', 'ProfileController@index')->name('profile');
    Route::put('/profile/update', 'ProfileController@update')->name('profile.update');
    Route::get('get/skor/habits', 'UsersPerfomanceController@getHabitsScore')->name('get.skor.habits');
});

Route::group(['middleware' => ['auth', 'role:admin']], function () {
    Route::resource('main-habits', 'MainHabitsController');
    Route::resource('sub-main-habits', 'SubMainHabitsController');
    Route::resource('habits', 'HabitsController')->except(['create']);
    Route::resource('lembaga', 'LembagaController');
    
    // add user institusi
    Route::get('lembaga/user/{id}', 'LembagaController@user')->name('lembaga.user');
    Route::post('lembaga/user/{id}/{action}', 'LembagaController@userstore')->name('lembaga.user.add');

    Route::resource('role', 'RoleController');
    Route::resource('group', 'GroupController');
    Route::resource('ayyamul-bidh', 'AyyamulBidhController');
    Route::resource('pengamalan-habits-umum', 'PengamalanHabitsUmumController');
    Route::resource('pengamalan-tadarus', 'RealitationTadarusController');
    Route::resource('pengamalan-zis', 'RealitationZisController');
});

Route::group(['middleware' => ['auth', 'role:admin instansi']], function () {
    Route::resource('group-institution', 'GroupInstitutionController');
});

Route::group(['middleware' => ['auth', 'role:admin|admin instansi']], function () {
    Route::resource('notification', 'NotificationController');
});

Route::group(['middleware' => ['auth', 'role:admin|user admin|admin instansi']], function () {
    Route::resource('user', 'UsersController');
    Route::resource('user-performance', 'UsersPerfomanceController');
    Route::get('userperformance/print', 'UsersPerfomanceController@print')->name('user-performance.print');
});

app/Models/Group.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    protected $fillable = [
        'name',
        'group_code',
        'institution_id',
    ];

    protected $with = [
        'institutions',
    ];

    protected static function boot()
    {
        parent::boot();

        static::deleting(function($grup) {
                if ($grup->user()->count() > 0) {
                    return false;
                }
            }
        );
    }

    public function user()
    {
        return $this->hasMany(User::class, 'group_id');
    }

    public function institutions()
    {
        return $this->belongsTo(Institution::class, 'institution_id');
    }

    public function getAdminGroupAttribute()
    {
        return User::where(['group_id' => $this->getAttribute('id'), 'role_id' => 3])->get();   
    }

    public function scopeFilter($query, $request)
    {
        if ($request === null) {
            return $query;
        }

        if ($request->has('nama')) {
            $query->where('name', 'LIKE', '%'.$request->get('nama').'%');
        }

        if ($request->has('kode_grup')) {
            $query->where('group_code', 'LIKE', '%'.$request->get('kode_grup').'%');
        }

        return $query;
    }
}

app/Http/Controllers/GroupInstitutionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\GroupInstitutionRequest;
use App\Repositories\GroupInstitutionRepository;

class GroupInstitutionController extends Controller
{
    public function __construct(GroupInstitutionRepository $repo)
    {
        $this->model = $repo;
        $this->title = 'Manajemen Grup';
        $this->module = 'group_institution';
        $this->request = GroupInstitutionRequest::class;
        $this->view = [
            'filter' => [
                'nama' => 'text',
                'kode_grup' => 'text',
            ],
        ];
    }

    public function index()
    {
        return parent::index()->with($this->view);
    }

    public function redirectFail($actionFrom, \Illuminate\Http\Request $request, $exception = null)
    {
        Session::flash('type', 'danger');
        return redirect()->back()->withMessage($exception);
    }

}

resources/views/admin/group_institution/create.blade.php
@extends('layouts.app')

@section('content')

		<!-- Horizontal Form -->
		<div class="box box-info">
		  <div class="box-header with-border">
			<h3 class="box-title">{{ $title_document }}</h3>
		  </div>
		  <!-- /.box-header -->
		  <!-- form start -->
		{{ Form::open(['route' => $module_url->store, 'method' => 'POST','files' => true]) }}
			<div class="box-body">
				@include($form)
				<hr>
				<h4>Insert User as Admin Group</h4>

				<div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
					<label for="name">Nama</label>
					{{ Form::text('user_name', old('name'), ['class' => 'form-control', 'id' => 'name', 'placeholder' => 'User Name']) }}
					{!! $errors->first('name', '<p class="help-block">:message</p>') !!}
				</div>

				<div class="form-group {{ $errors->has('email') ? ' has-error' : '' }}">
					<label for="email">Email</label>
					{{ Form::email('user_email', old('user_email'), ['class' => 'form-control', 'id' => 'user_email', 'placeholder' => 'User Email']) }}
					{!! $errors->first('user_email', '<p class="help-block">:message</p>') !!}
				</div>

				<div class="form-group {{ $errors->has('user_password') ? ' has-error' : '' }}">
					<label for="user_password">Password</label>
					{{ Form::password('user_password', ['class' => 'form-control', 'id' => 'user_password', 'placeholder' => 'Password']) }}
					{!! $errors->first('user_password', '<p class="help-block">:message</p>') !!}
				</div>
			</div>
			<!-- /.box-body -->
			<div class="box-footer">
				<button type="submit" class="btn btn-primary pull-right" dusk="btn-simpan">Simpan</button>
			</div>
			<!-- /.box-footer -->
		{{ Form::close() }}
		</div>

@endsection

resources/views/admin/group_institution/edit.blade.php
@extends('layouts.app')

@section('content')

		<!-- Horizontal Form -->
		<div class="box box-info">
		  <div class="box-header with-border">
			<h3 class="box-title">{{ $title_document }}</h3>
		  </div>
		  <!-- /.box-header -->
		  <!-- form start -->
		{{ Form::model($item, ['route' => [$module_url->update, $item->id], 'method' => 'PUT', 'files' => true]) }}
			<div class="box-body">
			  @include($form)
			</div>
			<!-- /.box-body -->
			<div class="box-footer">
				<button type="submit" class="btn btn-primary pull-right" dusk="btn-simpan">Simpan</button>
			</div>
			<!-- /.box-footer -->
		{{ Form::close() }}
		</div>

@endsection

resources/views/admin/group_institution/form.blade.php
<div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
	<label for="name">Nama</label>
	{{ Form::text('name', old('name'), ['class' => 'form-control', 'id' => 'name', 'placeholder' => 'Nama', 'required']) }}
	{!! $errors->first('name', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group {{ $errors->has('group_code') ? ' has-error' : '' }}">
	<label for="group_code">Kode</label>
	{{ Form::text('group_code', old('group_code'), ['class' => 'form-control', 'id' => 'group_code', 'placeholder' => 'Kode Grup', 'required']) }}
	{!! $errors->first('group_code', '<p class="help-block">:message</p>') !!}
</div>

@section('js')
	<script type="text/javascript">
	$('document').ready(function(){
		$("#group_code").on({
		keydown: function(e) {
			if (e.which === 32)
			return false;
		},
		change: function() {
			this.value = this.value.replace(/\s/g, "");
		}
		});

		$('#group_code').on('change', function(){
			this.value = this.value.toLowerCase();
		});
	});
	</script>
@endsection

resources/views/admin/group_institution/index.blade.php
@extends('layouts.app')

@section('content')
@include('layouts.filter')
{{-- {!! session() !!} --}}
<div class="clearfix"></div>
<br>
<div class="box box-success">
    <div class="box-header with-border ">
        <h3 class="box-title">{{ $title_document }}</h3>

    </div>
    <div class="box-body">
        @if ($items->isEmpty())
        <div class="alert alert-warning alert-dismissible" role="alert">
            <strong>Informasi</strong>

            Tidak Ada Data
        </div>
    @else
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th width="1%">#</th>
                        <th>Nama</th>
                        <th>Kode Grup</th>
                        <th>Admin</th>
                        <th width="15%">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($items as $item)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->group_code }}</td>
                            <td>
                                @if ($item->admin_group->count() == 0)
                                    {{ "-" }}
                                @endif
                                <ul>
                                    @foreach ($item->admin_group as $admin) 
                                        <li>{{ $admin->name }}</li>
                                    @endforeach
                                </ul>
                            <td>

                                <a href="{{ route($module_url->edit, $item->id) }}" class="btn btn-warning waves-effect waves-light" dusk="btn-option-edit-{{ $item->id }}"> <i class="fa fa-pencil-square-o"></i></a>
                                
                                <a class="btn btn-danger waves-effect waves-light" data-dismiss="modal" onclick="$('#delete-{{ $item->id }}').modal('show')" dusk="hapus-{{ $item->id }}"><i class="fa fa-trash"></i></a>

                                <div class="modal fade" role="dialog" tabindex="-1" id="delete-{{ $item->id }}">
                                    <div class="modal-dialog modal-sm" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4 class="modal-title">Perhatian!</h4>
                                            </div>
                                            <div class="modal-body">
                                                Hapus data, Yakin ?

                                                <div class="row" style="margin-top:50px;">
                                                    <div class="col-md-6">
                                                        <a href="{{ route('lembaga.destroy', $item->id) }}" data-method="DELETE" class="btn btn-danger" dusk="yesd-{{ $item->id }}">Ya, hapus!</a>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <a class="btn btn-inverse" data-dismiss="modal" onclick="$('#option-{{ $item->id }}').modal('show')">Batalkan</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

    @endif
    </div>
    <!-- /.box-body -->
    <div class="box-footer">
        <div>
            {{ $items->appends(Request::all())->links() }}
        </div>        
    </div>
    <!-- /.box-footer-->
</div>


@endsection

@section('script')
    <script src="{{ asset('js/laravel.js') }}"></script>
@endsection